#!/bin/bash
# Simple screenshot script, dependencies: grim, bemenu, imv, jq
# Choose directory to save screenshots and viewer

SHOTPATH=~/Bilder/screenshots
VIEWER=/usr/bin/imv-wayland

WINDOWS=`swaymsg -t get_tree | jq '.. | (.nodes? // empty)[] | select(.visible and .pid) | "\(.app_id) \(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)"'`
FOCUSED=`swaymsg -t get_tree | jq '.. | (.nodes? // empty)[] | select(.focused and .pid) | .rect | "\(.x),\(.y) \(.width)x\(.height)"'`

CHOICE=`bemenu -b -H 29 --tf=#ffffff --ff=#ffffff --hf=#4c7899 --fb=#000000 --tb=#000000 --nb=#000000 --hb=#000000 -p "Bitte Bereich wählen:" << EOF
Vollbild
Auswahl
Fokus
$WINDOWS
EOF`

FILENAME="${SHOTPATH}/screenshot-$(date +'%Y-%m-%d-%H%M%S.png')"
GRID=\"$(echo $CHOICE | awk ' {print $2,$3} ')

FILENAME_SHORT=${FILENAME: -32}

if [ "$CHOICE" = Vollbild ]
then
    grim "$FILENAME"
elif [ "$CHOICE" = Auswahl ]
then
    grim -g "$(slurp)" "$FILENAME"
elif [ "$CHOICE" = Fokus ]
then
    grim -g "$(eval echo $FOCUSED)" "$FILENAME"
else
    grim -g "$(eval echo $GRID)" "$FILENAME"
fi


WAHL=`bemenu -b -H 29 --tf=#ffffff --ff=#ffffff --hf=#4c7899 --fb=#000000 --tb=#000000 --nb=#000000 --hb=#000000 -p "Screenshot erstellt" << EOF
Öffnen
Speichern
Verwerfen
EOF`


if [ $WAHL = Öffnen ]
then
	$VIEWER $FILENAME &
	WAHL2=`bemenu -b -H 29 --tf=#ffffff --ff=#ffffff --hf=#4c7899 --fb=#000000 --tb=#000000 --nb=#000000 --hb=#000000  -p "${FILENAME_SHORT}"<< EOF
	Speichern
	Verwerfen
EOF`
	if [ $WAHL2 = Verwerfen ]
	then
		PID_VIEWER=$(pidof -s ${VIEWER}) 
		rm $FILENAME &
		kill -9 ${PID_VIEWER}
	else
		PID_VIEWER=$(pidof -s ${VIEWER}) 
		kill -9 ${PID_VIEWER}
		true
	fi
elif [ $WAHL = Verwerfen ]
then
	rm $FILENAME
else
	true
fi
exit 0
